In [1]:
name = "Athulya"
age = "20"

print("Name:", name)
print("Age:", age)


Name: Athulya
Age: 20


In [2]:
X = "Datascience is used to extract meaningful insights."
words = X.split()

for word in words:
    print(word)


Datascience
is
used
to
extract
meaningful
insights.


In [3]:
def multiply(num1, num2):
    result = num1 * num2
    return result

num1 = 5
num2 = 3
result = multiply(num1, num2)
print("The multiplication of", num1, "and", num2, "is:", result)


The multiplication of 5 and 3 is: 15


In [4]:
states = {
    'Maharashtra': 'Mumbai',
    'Tamil Nadu': 'Chennai',
    'Karnataka': 'Bengaluru',
    'Uttar Pradesh': 'Lucknow',
    'Gujarat': 'Gandhinagar'
}

print("States:")
for state in states.keys():
    print(state)

print("\nState Capitals:")
for capital in states.values():
    print(capital)


States:
Maharashtra
Tamil Nadu
Karnataka
Uttar Pradesh
Gujarat

State Capitals:
Mumbai
Chennai
Bengaluru
Lucknow
Gandhinagar


In [5]:
numbers = list(range(1, 1001))

print(numbers[:10])
print(numbers[-10:])
print(numbers[999])


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[991, 992, 993, 994, 995, 996, 997, 998, 999, 1000]
1000


In [6]:
matrix = [[1 if i == j else 0 for j in range(4)] for i in range(4)]

for row in matrix:
    print(row)


[1, 0, 0, 0]
[0, 1, 0, 0]
[0, 0, 1, 0]
[0, 0, 0, 1]


In [7]:
matrix = [[j + 1 + i * 3 for j in range(3)] for i in range(3)]
for row in matrix:
    print(row)


[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [9]:
import numpy as np
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

result = array1 + array2
print(result)


[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [10]:
from datetime import datetime, timedelta

start_date = datetime(2023, 2, 1)
end_date = datetime(2023, 3, 1)

date_range = []
current_date = start_date

while current_date <= end_date:
    date_range.append(current_date)
    current_date += timedelta(days=1)

for date in date_range:
    print(date.strftime('%d-%m-%Y'))


01-02-2023
02-02-2023
03-02-2023
04-02-2023
05-02-2023
06-02-2023
07-02-2023
08-02-2023
09-02-2023
10-02-2023
11-02-2023
12-02-2023
13-02-2023
14-02-2023
15-02-2023
16-02-2023
17-02-2023
18-02-2023
19-02-2023
20-02-2023
21-02-2023
22-02-2023
23-02-2023
24-02-2023
25-02-2023
26-02-2023
27-02-2023
28-02-2023
01-03-2023


In [13]:
import pandas as pd

dictionary = {'Brand': ['Maruti', 'Renault', 'Hyundai'], 'Sales': [250, 200, 240]}
df = pd.DataFrame(dictionary)

print(df)


     Brand  Sales
0   Maruti    250
1  Renault    200
2  Hyundai    240
